# Basic information.
title: Shawn Duong
blog: "shawn@home:~/blog"
description: Hacker. Programmer. Student. Teacher. That's me, Shawn Duong.
baseurl: ""

# Contact information.
email: business.shawnd@pm.me
twitter: shawndxyz
github: shawnduong

# Paginator setup.
permalink: /blog/:year-:month-:day/:title
paginate: 5
paginate_path: /blog/:num

# Plugins.
plugins:
  - jekyll-paginate
